version: "2"

plugins:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
  sonar-python:
    enabled: true
    config:
      tests_patterns:
      - tests/**/*


exclude_patterns:
- tests/**/*
- sitri.egg-info/**/*
- docs/**/*
- venv/**/*
- dist/**/*
- .github/**/*
