name: Deploy sitri

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel poetry attrs
        poetry config virtualenvs.create false --local && poetry install --no-dev --no-ansi -n
    - name: Test with pre-commit
      run: |
        pip install pre-commit
        pre-commit run -a
    - name: Build and publish
      run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build
