name: Package

on:
  pull_request:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Deps
      run: |
        python -m pip install --upgrade pip
        pip install poetry pre-commit bumpversion
        poetry install
    - name: Configure git
      run: |
        git config --global user.email "egnod@ya.ru"
        git config --global user.name "Alexander Lavrov"
    - name: Publish pypi
      run: |
        poetry build
        poetry publish -u __token__ -p ${{ secrets.pypi_token }}
